version: '3.9'

services:
  aesm:
    image: initc3/linux-sgx:2.19-ubuntu22.04
    devices:
      - /dev/isgx
    volumes:
      - aesmd-socket:/var/run/aesmd
    user: aesmd
    working_dir: /opt/intel/sgx-aesm-service/aesm
    environment:
      LD_LIBRARY_PATH: /opt/intel/sgx-aesm-service/aesm
    command: ./aesm_service --no-daemon

  gramine:
    image: gramine:sgx
    build:
      context: .
      dockerfile: sgx.Dockerfile
    depends_on:
      - aesm
    devices:
      - /dev/isgx
    security_opt:
      - seccomp:unconfined
    volumes:
      - aesmd-socket:/var/run/aesmd

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"
